config/routes.rb
St001::Application.routes.draw do

   resources :pages

   get "/how_it_works" => "pages#how", :as => "how_it_works"
   get "/win_urBeats_by_dre" => "pages#beats", :as => "win_urBeats_by_dre"

   get "email_confirms/new"

   match '/sharrre' => 'Rsocialize#sharrre'

   match '/deals/new/:id' => 'deals#new', :as => 'newdealwithproduct'


   get "invite/products/:id/" => "products#invite", :as => "invite_product"
   get "invite/deal/:id/" => "deals#invite", :as => "invite_deal"
   get "invite/home/" => "home#invite", :as => "invite_home"
   post "invite/email/" => "referral#email", :as => "invite_email"
   match 'invite/:id' => 'referral#redirect', :as => 'accept_referral'

   resources :groups
   resources :troopfails
   resources :troopcompletes
   resources :locations
   resources :categories
   resources :trooplinks
   resources :deals
   resources :orders
   resources :likes, :only => [:create, :destroy]
   resources :password_resets

   resources :products do
      post :want_product, :on => :member
   end

   get "home/index"
   resources :roles
   resources :likes
   resource :cart

   get "paypal_express/checkout"
   get "paypal_express/cancel"
   get "paypal_express/review"
   get "paypal_express/purchase"
   get "paypal_express/refund"
   get "paypal_express/notify"
   post "paypal_express/notify"
   
   get "/check_duplicates" => "products#duplicate", :as => "product_duplicate"
   get "/like_and_view/:id/" => "products#like_and_view", :as =>"producut_like_and_view"
   get "/product_url_scrape" => "scrape#scrape", :as => "scrape_url_images"

   match "/products/add_new_comment" => "products#add_new_comment", :as => "add_new_comment_to_produdcts", :via => [:post]
   match "/deals/add_new_comment" => "deals#add_new_comment", :as => "add_new_comment_to_deals", :via => [:post]
  
   get "remove_comment/:id/" => "products#remove_comment", :as => "remove_comment"
   
   get "shareproduct/:id/" => "products#share", :as => "share_product"
   get "sharedeal/:id/" => "deals#share", :as => "share_deal"

   get "followuser/:id/" => "follows#followuser", :as => "followuser"
   get "unfollowuser/:id/" => "follows#unfollowuser", :as => "unfollowuser"
   get "following/:id/" => "follows#following", :as => "following"
   get "followers/:id/" => "follows#followers", :as => "followers"

   match '/search/:query/:qcategory' => 'search#search', :as => 'search'
   #match '/search/:query' => 'search#search', :as => 'search'
   
   match '/search' => 'search#search', :as => 'search'

   match 'auth/:provider/callback', to: 'sessions#createfacebook'
   match 'auth/failure', to: redirect('/')
   match 'signout', to: 'sessions#facebook', as: 'signout'


   get "logout" => "sessions#destroy", :as => "logout"
   get "login" => "sessions#new", :as => "login"
   get "admin_users" => "users#view_user", :as => "admin_users"
   get "admin_merchants" => "users#view_merchant", :as => "admin_merchants"
   get "admin_products" => "products#view", :as => "admin_products"
   get "admin_deals" => "deals#view", :as => "admin_deals"
   get "admin_locations" => "locations#view", :as => "admin_locations"
   get "admin_categories" => "categories#view", :as => "admin_categories"
   get "admin_orders" => "orders#view", :as => "admin_orders"
   get "admin_referrals" => "referral#view", :as => "admin_referrals"


   get "admin_pages" => "pages#view", :as => "admin_pages"
   get "register" => "users#new", :as => "register"
   get "dashboard" => "users#dashboard", :as => "userprofile"

   get "sitemap.xml.gz" => "sitemap#file"

   match "/modalshow/:id" => "deals#modalshow"

   root :to => "products#homepage"
   resources :users
   resources :sessions

   get "email_confirms/new"
   resources :email_confirms


   match "/resend/:id" => "users#resend_confirmation_email"

   match 'contactmessager' => 'contactmessager#new', :as => 'contactmessager', :via => :get
   match 'contactmessager' => 'contactmessager#create', :as => 'contactmessager', :via => :post
   
   match 'troops/:id' => 'deals#show', :as => 'troop_catch'

end

app/views/shared/_admin_menu.erb
<% if current_user.role_id == 1 %>
    <a class = "btn" href = "/admin_users">Users</a>
    <a class = "btn" href = "/admin_merchants">Merchants</a>
    <a class = "btn" href = "/admin_products">Products</a>
    <a class = "btn" href = "/admin_deals">Deals</a>
    <a class = "btn" href = "/admin_categories">Categories</a>
    <a class = "btn" href = "/admin_referrals">Referrals</a>
    <!-- <a class = "btn" href = "/admin_locations">Locations</a> -->
<% end %>

app/views/shared/_footer.html.erb
	<div class="navbar navbar-fixed-bottom bottomnav">
	   <div class="navbar-inner floatingmenu">
		   <div class="container footercenter">
            <a href="/how_it_works">How it works</a>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;
				<a href = '/pages/contact-us/'>Contact Us</a>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;<a href = '/pages/terms-and-conditions'>Terms and Conditions</a>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;<a href = '/pages/privacy-and-cookies'>Privacy and Cookies Policies</a>
		   </div>
		</div>
	</div>

app/views/shared/_modals.html.erb
<% session[:return_to] = request.url %>



<!-- Modal login ONLY if not logged in -->
<div id="register_popup" style = "display:none;">

	<div style = "float:left;width:100%;">
		<a class="register_popup_close fa-button" style = "position: absolute;top: 0px;right: 0px;" ><i class="fa fa-close" style = "width:14px;"></i></a></a>
	</div>

	<h3 style="display:none;margin:20px !important; text-align:center; font-weight: bold;font-size: 1.5em;" id="successtext">Welcome to FRNZY!</h3>

	<% unless current_user %>
	<div class="removemeonregister">
		  <div style  = "max-width:280px; width: 90%; margin:2.5em auto 0;">
		  	<a href="/auth/facebook" id="sign_in"><img style = "width:100%;" src = "/images/signin-facebook-large.png" /></a>
		  </div>
		<div style="text-align:center;font-weight:bold;margin-top:10px;">OR</strong></div>
	</div>



	<% end %>

	<div id = "registerupdate"></div>
	<% @user = User.new %>
	<%= form_for @user, :remote => true do |f| %>
		<%= f.text_field :email, :placeholder => 'Email' %><br/>
		<%= f.text_field :username, :placeholder => 'Username' %><br/>
		<%= f.text_field :first_name, :placeholder => 'First name' %><br/>
		<%= f.text_field :last_name, :placeholder => 'Last name' %><br/>
		<%= f.password_field :password, :placeholder => 'Password' %><br/>
		<%= f.password_field :password_confirmation, :placeholder => 'Confirm password' %><br/>
		<div class="field" style = "display:none;">
			<label for="photo">Image</label>
			<%= f.file_field :photo %><br />
		</div> 
		<div class="field" style="display:none">
		 	<%= f.label :role_id %>
			<select id="user_role_id" name="user[role_id]">
			<option value="2">merchant</option>
			<option value="3" selected="selected">user</option></select>
		</div> 

		<div class="removemeonregister" style = "width: 60px; margin:auto; padding-bottom: 70px;display:none;">
			<%= f.submit 'JOIN', :class => 'frnzyHeadBtn static join_troop_btn singleLine registerButton', :style => "padding: 25px 11px 35px 10px !important; font-size: 18px !important;" %>
		</div>	

		<div style = "width:100%;">
			<a href="#" class="fa-button registerButton_clicker" style = "position: relative;margin-top: 20px;margin-bottom: 0px;width: 90px;margin-left: -45px;left: 50%;text-align: center;">
				Join
			</a>
		</div>

	<% end %>  	

	<div class = "removemeonregister" style="padding-top:10px;padding-bottom:0px;margin-bottom:0px; text-align: center;width:100%;float:left;"><p>By joining you agree to our <a href = '/pages/terms-and-conditions'>Terms and Conditions</a> and <a href = '/pages/privacy-and-cookies'>Privacy Policy</a></p></div>

</div>


  







<%# Share Modal %>
<div class="ShareModal" id = "generate_share">
</div>



<%# Invite Modal %>
<div id="invite_popup">
	<div class="invite_holder">		
	</div>
</div>




<%# Add product Modal %>
 <% @product = Product.new %>
 <% @categories = Category.all %>
<div id="add_popup" style = "display:none;">
	<div class="add_holder allowbig">	
<div class = "responsive_add_wizard">
	<script>
		$('.navbar').addClass('overide_margin_bottom');
	</script>
	<a class="add_popup_close fa-button" style = "position: absolute;top: 0px;right: 0px;" ><i class="fa fa-close" style = "width:14px;"></i></a></a>

	<% if current_user %>		

		<div class="add_product_name wizard_box" style="clear: both">
			<div class = "circle_half_wrapper">
			<div class="add_product_circle blue">
				<h2>Please enter the full name of the product</h2>
			</div>
			</div>
			<div class="add_product_title_frm">
				<%= form_tag(product_duplicate_path, method: "get", remote: true) do %>
					<%= text_field_tag :name, nil, :placeholder => "Product Name",:required => true %>
					<div class="add_product_btn" style = "display:none;">
						<%= submit_tag("NEXT", class: 'add_product_next_step add_product_next_step_1') %>
					</div>

					<div style = "width:100%;">
						<a href="#" class="fa-button add_product_clicker_1" style = "margin-top:20px;margin-bottom:0px;width: 100px;position:relative;margin-left:-50px;left:50%;">
							Next
						</a>
				    </div>


				<% end %>
			</div>
  
		</div>
		<div class="add_product_similar wizard_box" style="display:none">
			
			<div class = "circle_half_wrapper">
				<div class="add_product_circle blue">
				<h2>Is your product already listed on FRNZY?</h2>
			</div>
			</div>

			<div class="add_product_title_frm">
			
				<div style = "margin-top:10px;" class="add_product_product_title"></div>
					
					<a href="#" class="fa-button product_not_similar_clicker" style = "margin-top:10px;margin-bottom:10px;position:relative;margin-left:-110px;left:50%;width:220px;">
						<i class="fa fa-exclamation-circle"></i>My product is not listed
					</a>

			</div>

			<div class="similar_products_list">
			</div>

			<div class="clearfix"></div>
			
			<a href="#" class="fa-button product_not_similar_clicker" style = "margin-top:10px;margin-bottom:0px;position:relative;margin-left:-110px;left:50%;width:220px;">
				<i class="fa fa-exclamation-circle"></i>My product is not listed
			</a>

		</div>
		<div class="add_product_url wizard_box" style="display:none">
			<div class = "circle_half_wrapper">
				<div class="add_product_circle pink">
				<h2>Please enter the URL of the product</h2>
			</div>
			</div>
			<div class="add_product_url_frm">
				<div class="add_product_product_title"></div>
				<%= form_tag(scrape_url_images_path, method: "get", remote: true, :id => "scrape_form" ) do %>
					<%= text_field_tag :url, nil, :placeholder => "http://www...",:required => true %>
					<div class="add_product_btn" style = "display:none;">
						<%= submit_tag("NEXT", class: 'add_product_next_step add_product_next_step_2') %>
					</div>

					<div style = "width:100%;">
						<a href="#" class="fa-button add_product_clicker_2" style = "margin-top:20px;margin-bottom:0px;width: 100px;position:relative;margin-left:-50px;left:50%;">
							Next
						</a>
					</div>

				<% end %>
				<div class="add_product_url_loading" style="display:none">
					We're looking for your product<br/>
					<i class="fa fa-spinner fa-pulse" style = "color:#ff1f88;font-size:40px;margin-top:15px;"></i>
				</div>
				<% content_for :script do %>
				  <script type="text/javascript">
				    $('.add_product_url form').on('submit', function(){
				    	$('.add_product_url_loading').show();
				    	$('.add_product_clicker_2').hide();
				    	$('.add_product_url_frm input[type="submit"]').hide();
				    	$('.add_product_url .add_product_error').hide();

						if(window.frnzyAnim)
						{
							clearInterval(window.frnzyAnim);
						}
					    (function(){
						    var circle1 = $('.add_product_anim_1').css('visibility','hidden');
						    var circle2 = $('.add_product_anim_2').css('visibility','hidden');
						    var circle3 = $('.add_product_anim_3').css('visibility','hidden');
						    var circle4 = $('.add_product_anim_4').css('visibility','hidden');
						    var circle5 = $('.add_product_anim_5').css('visibility','hidden');
						    var status = -1;

						    window.frnzyAnim = setInterval(function(){
						    	status++;
						    	switch(status)
						    	{
						    		case 0:
					    				circle4.animate({opacity: 0},500, function(t){
					    					$(this).css({'visibility':'hidden'});
					    				});		
						    			circle1.css({'visibility':'visible', 'opacity':0}).animate({opacity: 1.0},500);
						    			break;
						    		case 1:
					    				circle5.animate({opacity: 0},500, function(t){
					    					$(this).css({'visibility':'hidden'});
					    				});		
						    			circle2.css({'visibility':'visible', 'opacity':0}).animate({opacity: 1.0},500);
						    			break;
					    			case 2:
					    				circle3.css({'visibility':'visible', 'opacity':0}).animate({opacity: 1.0},500);
						    			break;
						    		case 3:
						    			circle4.css({'visibility':'visible', 'opacity':0}).animate({opacity: 1.0},500);
						    			circle1.animate({opacity: 0},500, function(t){
						    				$(this).css({'visibility':'hidden'});
						    			});
						    			break;
					    			case 4:
						    			circle5.css({'visibility':'visible', 'opacity':0}).animate({opacity: 1.0},500);
						    			circle2.animate({opacity: 0},500, function(t){
						    				$(this).css({'visibility':'hidden'});
						    			});
						    			break;
					    			case 5:
					    				circle3.animate({opacity: 0},500, function(t){
					    					$(this).css({'visibility':'hidden'});
					    				});
					    				status = -1;
						    			break;
					    			default:
					    				status = -1;
						    	}
						    },250)
					    })();
				    });
				  </script>
				<% end %>
			</div>
			<div class="add_product_error" style="display:none">

			</div>
		</div>
		<div class="add_product_image wizard_box" style="display:none">
			<div class = "circle_half_wrapper">
				<div class="add_product_circle green">
				<h2>Please select a photo of your product</h2>
			</div>
			</div>
			<div class="add_product_url_frm">
				<div class="add_product_product_title"></div>
				<div class="add_product_product_url"></div>
			</div>
			
		</div>
		<div class="add_product_confirm wizard_box" style="<%= 'display:none' if @product.errors.any? == false %>">
			<div class = "circle_half_wrapper">
				<div class="add_product_circle yellow">
				<h2>Choose a category and add your product</h2>
			</div>
			</div>
			<div class="add_product_selected_img"></div>
			<div class="add_product_frm">
				<%= form_for(@product, :html => { :multipart => true }) do |f| %>
				   <% if @product.errors.any? %>
				      <div id="error_explanation">
				         <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
				         <ul>
				            <% @product.errors.full_messages.each do |msg| %>
				               <li><%= msg %></li>
				            <% end %>
				         </ul>
				      </div>
				   <% end %>
				  
				   <div>
						<div class="field">
							 <%= f.text_field :name %>
						</div>
						<div class="field">
							 <%= f.text_field :product_url %>
						</div>

				      <div class="field" style="float: left;width: 100%;">
				      	 <% options = @categories.unshift Category.new(id: 0, name: 'Select a category') %>
				         <%= f.collection_select :category_id, options, :id, :name  %>
				      </div>

						<%= f.hidden_field :image_url %>				
						<%= f.hidden_field :slug, :value => SecureRandom.hex(10) %>
						<%= f.hidden_field :user_id, :value => current_user.id %>

						<div class="add_product_btn" style = "display:none;">
							<%= f.submit "Add to FRNZY", :class => "add_product_next_step_3", :style => ""  %>
						</div>

						<div style = "width:100%;">
							<a href="#" class="fa-button add_product_clicker_3" style = "margin-top:20px;margin-bottom:0px;width: 150px;margin-left:-75px;left:50%;position:relative;">
								<i class="fa fa-plus-circle"></i>Add to FRNZY
							</a>
						</div>

				   </div>

				<% end %>
			</div>
		</div>
	<% else %>
			<div style="padding-top:16px;" class = "close_on_click">
				<h2>Please <a href = "#" class = "open_login">sign in</a> to<br>add a product</h2>
			</div>
	<% end %>  
	<script>
		//$('.frnzyFeedback').hide();
	</script>

</div>

</div>

</div>

app/views/shared/_zette_menu.html.erb
    <!-- Zetta Menu 2 -->
  <ul onClick="" class="zetta-menu zm-response-simple zm-full-width zm-effect-fade">



<!-- Multilevel Dropdown Menu -->
      <li style = "text-align :left;" id = "products_menu">

        <a id = "menu_open_button" ><i id = "product_icon" class="fa fa-bars"></i>Products<i class="zm-caret fa fa-angle-down"></i></a>
        <a style = "display:none;" id = "menu_close_button" ><i id = "product_icon" class="fa fa-close" style = "" ></i>Products<i class="zm-caret fa fa-angle-down"></i></a>


      <ul class="w-300 set_document_height" style = "overflow:auto;">

             <h3 style = "margin-bottom:10px;">Search for products and deals</h3>

        <li class="zm-search zm-search-mobile">
     
    

          <form action = "/search/">
            <%= text_field_tag :query, params[:query], {:class => "searchtext", :style=>"width:100%;", :placeholder=>"Product name" }%>
            <label for="search-1" class="fa fa-search"></label>
          </form>


    </li>


        <h3 style = "margin-bottom:10px;margin-top:10px;">Browse by category</h3>

   <div class = "maseplese">

       <li class = "menu_half">
                              <a href="/categories/arts-&amp;-entertainment">Arts &amp; Entertainment</a>

     
                                  <li class = "menu_half">

                              <a href="/categories/clothes-shoes-&amp;-jewellery">Clothes, Shoes &amp; Jewellery</a>


                           </li>
                         
                           </li>
                                  <li class = "menu_half">

                              <a href="/categories/electricals-&amp;-computers">Electricals &amp; Computers</a>


                           </li>
                                  <li class = "menu_half">

                              <a href="/categories/toys-children-&amp;-baby">Toys, Children &amp; Baby</a>


                           </li>
                                  <li class = "menu_half">

                              <a href="/categories/car-&amp;-motorbike">Car &amp; Motorbike</a>


                           </li>
                                  <li class = "menu_half">

                              <a href="/categories/photography">Photography</a>


                           </li>
                                  <li class = "menu_half">

                              <a href="/categories/health-&amp;-beauty">Health &amp; Beauty</a>


                           </li>
                                  <li class = "menu_half">

                              <a href="/categories/home-gardens-pets-&amp;-DIY">Home, Gardens, Pets &amp; DIY</a>


                           </li>
                                  <li class = "menu_half">

                              <a href="/categories/audio-&amp;-phones">Audio &amp; Phones</a>


                           </li>
                                  <li class = "menu_half">

                              <a href="/categories/food-&amp;-drink">Food &amp; Drink</a>


                           </li>
  

    <li class = "menu_half">

                              <a href="/categories/sports-&amp;-leisure">Sports &amp; Leisure</a>


                           </li>

                           </div>

        <li class="menu_footer">
          <a href="/pages/contact-us/">Contact</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="/pages/terms-and-conditions">Terms and Conditions</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="/pages/privacy-and-cookies">Privacy Policy</a>
        </li>

      </ul>
    </li>
    <!-- /Multilevel Dropdown Menu -->

      <!-- Simple Item -->
    <li class="lessthan450 zm"><a class = "add_popup_open" hrecirclef="#"><i class="fa fa-plus-circle"></i>Add</a></li>
    <!-- /Simple Item -->


      <!-- User Login -->
    <li style = "display:none;" class="lessthan450  zm-content"><a><i class="zm-single-icon fa fa-plus-circle"></i></a>
      <div class="w-350">
        <h3>Add a product to FRNZY</h3>
        <form action="">
          <input placeholder="Product name" name="name" type="text">
          <input placeholder="Product url" name="url" type="text">
          <input class="zm-button" type="submit" value="Add">
        </form>
      </div>
    </li>
    <!-- /User Login -->

    <!-- Logo -->
    <li class="zm-logo"><a href="/"><img title="zettaMenu logo image" src="/images/logo.png" alt=""></a></li>
    <!-- /Logo -->

    <!-- Simple Item -->
    <li style = "display:none;" class="zm"><a href="#"><i class="fa fa-home"></i>Active</a></li>
    <!-- /Simple Item -->

  <!-- User Login -->
      
      <% unless current_user %>



    <li style = "" class="zm-content zm-right-item zm-right-align" id = "profile_menu">

      <a id = "profile_menu_open_button"><i class="zm-single-icon fa fa-user login_icon"></i></a>
      <a style = "display:none;" id = "profile_menu_close_button"><i class="zm-single-icon fa fa-close login_icon"></i></a>

        <div class="w-300 login_menu">
          <h3>Sign in to FRNZY!</h3>


          <%= form_tag sessions_path, :remote => true do %>
            <div id = "loginupdate"></div>
            <input id="email" name="email" placeholder="Email"type="text">
            <input id="password"  placeholder="Password" name="password" type="password">
            <input class="fa-button" type="submit" value="Sign in">
         <% end %>



          <% session[:return_to] = request.url %>
          <!-- Modal login ONLY if not logged in -->
        
        <div style = "text-align:center;" class = "forgot_and_register">

          <p style="margin-top:20px;"><%= link_to "Forgotten password?", new_password_reset_path %><br>Not a member yet? <a class = "register_popup_open" href="#" style = "text-decoration:underline;">Get started</a></p>
        
        </div>
            <!-- <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button> -->
         
       
          
          <script>
            $(document).ready(function(){
              $('.NotAmember a').on('click', function(e){
                e.preventDefault();

                $('#myModal').modal('hide');
                setTimeout(function(){
                  $('#myModalRegister').modal('show');
                }, 300);
                return false;
              });
            });
          </script>





 <div style = "text-align:center;font-weight:bold;margin-top:10px;">OR</div>
 
        <div style  = "margin-top:5px;width:250px; margin:0pt auto;"><a href="/auth/facebook" id="sign_in"><img src = "/images/signin-facebook-large.png" /></a></div>

        </div>

      <% else %>

        <li style = "" class="zm-content zm-right-item zm-right-align" id = "profile_menu">
          <a id = "profile_menu_open_button"><i class="zm-single-icon fa fa-user login_icon"></i></a>
          <a style = "display:none;" id = "profile_menu_close_button"><i class="zm-single-icon fa fa-close login_icon"></i></a>

          <ul class="w-200 profiledropdown">


                  <div class="menu_profile_image">
                    <div>
                      <% if current_user.provider == 'facebook' %>
                         <% theproductimageurl = 'https://graph.facebook.com/'+current_user.uid.to_s+'/picture?type=large' %>
                      <div class = "facebookimage" style = "background-image:url('<%= theproductimageurl %>');" ></div>
                      <% else %>
                         <%= image_tag current_user.photo.url(:small) %>
                      <% end %>
                   </div>
                 </div>






            <li style = "margin-top: 0px;"><a class = "add_popup_open" href="#"><i class="fa fa-plus-circle fa-fw"></i> Add product</a></li>
            <li style = "margin-top: 0px;">
              <%= link_to '/invite/home', :class => "", :remote => true do %>
                <i class="fa fa-user-plus"></i>
                Invite Friends
              <% end %>
            </li>
            <li style = "margin-top: 0px;">
              <%= link_to current_user, :class => "" do %>
                <i class="fa fa-user"></i>
                View profile
              <% end %>
            </li>
            <li style = "margin-top: 0px;"><a href="/win_urBeats_by_dre"><i class="fa fa-headphones fa-fw"></i> WIN urBeats</a></li>
            <li style = "margin-top: 0px;"><a href="/dashboard"><i class="fa fa-tachometer fa-fw"></i> Dashboard</a></li>
            <li style = "margin-top: 0px;"><a href="/how_it_works"><i class="fa fa-question-circle fa-fw"></i> How it works</a></li>



            <li style = "margin-top: 0px;"><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Sign out</a></li>
          </ul>
        </li>


       <% if current_user.role_id == 1 %>


        <li style = "" class="lessthan450 zm-content zm-right-item zm-right-align" id = "admin_menu">
          <a id = "admin_menu_open_button"><i class="zm-single-icon fa fa-cog login_icon fa-fw"></i></a>
          <a style = "display:none;" id = "admin_menu_close_button"><i class="zm-single-icon fa fa-close login_icon fa-fw"></i></a>

          <ul class="w-200 admindropdown" style = "text-align:left;">
            <li style = "margin-top: 0px;"><a href = "/admin_orders">View all transactions</a></li>
            <li style = "margin-top: 0px;"><a href = "/admin_users">Manage users (<%= @users_new_count %>)</a></li>
            <li style = "margin-top: 0px;"><a href = "/admin_merchants">Manage merchants (<%= @merchants_new_count %>)</a></li>
            <li style = "margin-top: 0px;"><a href = "/admin_products">Manage products (<%= @products_new_count %>)</a></li>
            <li style = "margin-top: 0px;"><a href = "/admin_deals">Manage deals (<%= @deals_new_count %>)</a></li>
            <li style = "margin-top: 0px;"><a href = "/admin_categories">Manage categories</a></li>
            <li style = "margin-top: 0px;"><a href = "/admin_pages">Edit pages</a></li>
            <li style = "margin-top: 0px;"><a href = "/admin_referrals">View Referrals</a></li>
            <li style = "margin-top: 0px;"><%= link_to 'Edit admin profile', edit_user_path(current_user) %></li>
          </ul>
        </li>

        <% end %>


      <% end %>








     

    
    <!-- Search Place -->
    <li class="zm-search zm-right-item" style = "display:none;">
      <form action="">
        <input id="search-2" name="search" type="search">
        <label for="search-2" class="fa fa-search"></label>
      </form>
    </li>
    <!-- /Search Place --> 



    <li class="lessthan450 zm-right-item zm-right-align "><a href="/how_it_works"><i class="fa fa-question-circle"></i>How it works</a></li>


  </ul>
  <!-- /Zetta Menu 2 -->