config/routes.rb
St001::Application.routes.draw do

   resources :pages

   get "/how_it_works" => "pages#how", :as => "how_it_works"
   get "/win_urBeats_by_dre" => "pages#beats", :as => "win_urBeats_by_dre"

   get "email_confirms/new"

   match '/sharrre' => 'Rsocialize#sharrre'

   match '/deals/new/:id' => 'deals#new', :as => 'newdealwithproduct'


   get "invite/products/:id/" => "products#invite", :as => "invite_product"
   get "invite/deal/:id/" => "deals#invite", :as => "invite_deal"
   get "invite/home/" => "home#invite", :as => "invite_home"
   post "invite/email/" => "referral#email", :as => "invite_email"
   match 'invite/:id' => 'referral#redirect', :as => 'accept_referral'

   resources :groups
   resources :troopfails
   resources :troopcompletes
   resources :locations
   resources :categories
   resources :trooplinks
   resources :deals
   resources :orders
   resources :likes, :only => [:create, :destroy]
   resources :password_resets

   resources :products do
      post :want_product, :on => :member
   end

   get "home/index"
   resources :roles
   resources :likes
   resource :cart

   get "paypal_express/checkout"
   get "paypal_express/cancel"
   get "paypal_express/review"
   get "paypal_express/purchase"
   get "paypal_express/refund"
   get "paypal_express/notify"
   post "paypal_express/notify"
   
   get "/check_duplicates" => "products#duplicate", :as => "product_duplicate"
   get "/like_and_view/:id/" => "products#like_and_view", :as =>"producut_like_and_view"
   get "/product_url_scrape" => "scrape#scrape", :as => "scrape_url_images"

   match "/products/add_new_comment" => "products#add_new_comment", :as => "add_new_comment_to_produdcts", :via => [:post]
   match "/deals/add_new_comment" => "deals#add_new_comment", :as => "add_new_comment_to_deals", :via => [:post]
  
   get "remove_comment/:id/" => "products#remove_comment", :as => "remove_comment"
   
   get "shareproduct/:id/" => "products#share", :as => "share_product"
   get "sharedeal/:id/" => "deals#share", :as => "share_deal"

   get "followuser/:id/" => "follows#followuser", :as => "followuser"
   get "unfollowuser/:id/" => "follows#unfollowuser", :as => "unfollowuser"
   get "following/:id/" => "follows#following", :as => "following"
   get "followers/:id/" => "follows#followers", :as => "followers"

   match '/search/:query/:qcategory' => 'search#search', :as => 'search'
   #match '/search/:query' => 'search#search', :as => 'search'
   
   match '/search' => 'search#search', :as => 'search'

   match 'auth/:provider/callback', to: 'sessions#createfacebook'
   match 'auth/failure', to: redirect('/')
   match 'signout', to: 'sessions#facebook', as: 'signout'


   get "logout" => "sessions#destroy", :as => "logout"
   get "login" => "sessions#new", :as => "login"
   get "admin_users" => "users#view_user", :as => "admin_users"
   get "admin_merchants" => "users#view_merchant", :as => "admin_merchants"
   get "admin_products" => "products#view", :as => "admin_products"
   get "admin_deals" => "deals#view", :as => "admin_deals"
   get "admin_locations" => "locations#view", :as => "admin_locations"
   get "admin_categories" => "categories#view", :as => "admin_categories"
   get "admin_orders" => "orders#view", :as => "admin_orders"
   get "admin_referrals" => "referral#view", :as => "admin_referrals"


   get "admin_pages" => "pages#view", :as => "admin_pages"
   get "register" => "users#new", :as => "register"
   get "dashboard" => "users#dashboard", :as => "userprofile"

   get "sitemap.xml.gz" => "sitemap#file"

   match "/modalshow/:id" => "deals#modalshow"

   root :to => "products#homepage"
   resources :users
   resources :sessions

   get "email_confirms/new"
   resources :email_confirms


   match "/resend/:id" => "users#resend_confirmation_email"

   match 'contactmessager' => 'contactmessager#new', :as => 'contactmessager', :via => :get
   match 'contactmessager' => 'contactmessager#create', :as => 'contactmessager', :via => :post
   
   match 'troops/:id' => 'deals#show', :as => 'troop_catch'

end

app/models/deal.rb
class Deal < ActiveRecord::Base

   extend FriendlyId
   friendly_id :slug

   belongs_to :user
   belongs_to :product
   belongs_to :location
   has_many :trooplinks, :dependent => :destroy
   has_many :troopcompletes, :dependent => :destroy
   has_many :troopfails, :dependent => :destroy

   has_many :orders, :dependent => :destroy

   accepts_nested_attributes_for :trooplinks
   accepts_nested_attributes_for :troopcompletes
   accepts_nested_attributes_for :troopfails

   attr_accessible :auction_end, :isenabled, :product_id, :slug, :status, :troop_limit, :price, :user_id, :location_id, :published_at_date, :published_at_time, :end_count, :popularity, :featured

   attr_accessible :troop_rrp
   validates_presence_of :price
   validates_presence_of :troop_limit
   validates_presence_of :troop_rrp, :message => "^RRP can't be blank"
   validates_presence_of :auction_end

   validates_presence_of :product_id
   validates_presence_of :user_id
   validates_uniqueness_of :slug

   acts_as_commentable

   #after_create :send_want_emails

   def send_want_emails
      if self.product.likes.count > 0 
         self.product.likes.each do |like|
            like.user.delay.new_deal_email(self)
         end
      end
   end

   def percentsaving
       saving = ((1-(self.price/self.troop_rrp))*100).round()
       return saving.to_i
   end

   def the_transaction_status
      if troopcompletes.first.transaction_status == 1
         return 'Completed'
      else
         return 'Incomplete'
      end
   end

   def self.search(search)
      if search
         joins(:product).where('name ilike ?', "%#{search}%")
      else
         find(:all)
      end
   end

   def self.searchwithcat(search,cat)
      catob = Category.where('slug = ?', cat)
      if search
         joins(:product).where('name ilike ? AND category_id = ?', "%#{search}%", catob)
      else
         find(:all)
      end
   end

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

   include ActiveMerchant::Billing
   include PaypalExpressHelper

   layout "troop", :only => [ :modalshow ]
   helper_method :sort_column, :sort_direction
   before_filter :check_expirary

   layout 'application'

   def index
      raise ActionController::RoutingError.new('No such page')
   end

   def share
      @deal = Deal.find(params[:id])
      respond_to do |format|
         format.js
      end
   end

   def invite
      @deal = Deal.find(params[:id])
      @user = current_user
      if Referral.uniq.exists?(:user_id => @user.id, :deal_id => @deal.id)  
         @referral = Referral.where(:user_id => @user.id, :deal_id => @deal.id).first
      else
         @referral = Referral.new
         @referral.referral_code = rand(36**10).to_s(36)
         @referral.deal = @deal
         @referral.user = @user
         @referral.save
      end
      respond_to do |format|
         format.js
      end
   end

   def view

      if params[:search].nil?
         @deals = Deal.where("status = ? AND isenabled = ?", '1', '1')
      else
         @deals = Deal.search(params[:search])
         @deals = @deals.where(:status => ['1'])
         @deals = @deals.where(:isenabled => ['1'])
      end
      if params[:direction] == 'desc'
         @deals = @deals.sort_by{|e| e[params[:sort]]}.reverse!
      else
         @deals = @deals.sort_by{|e| e[params[:sort]]}
      end
      @deals = @deals.paginate(:page => params[:page_live], :per_page => 10)

      if params[:search].nil?
         @dealscompleted = Deal.where("status = ? AND isenabled = ?", '2', '1')
      else
         @dealscompleted = Deal.search(params[:search])
         @dealscompleted = @dealscompleted.where(:status => ['2'])
         @dealscompleted = @dealscompleted.where(:isenabled => ['1'])
      end

      if params[:direction] == 'desc'
         @dealscompleted = @dealscompleted.sort_by{|e| e[params[:sort]]}.reverse!
      else
         @dealscompleted = @dealscompleted.sort_by{|e| e[params[:sort]]}
      end
      @dealscompleted = @dealscompleted.paginate(:page => params[:page_completed], :per_page => 10)

      if params[:search].nil?
         @dealsexpired = Deal.where("status = ? AND isenabled = ?", '3', '1')
      else
         @dealsexpired = Deal.search(params[:search])
         @dealsexpired = @dealsexpired.where(:status => ['3'])
         @dealsexpired = @dealsexpired.where(:isenabled => ['1'])
      end

      if params[:direction] == 'desc'
         @dealsexpired = @dealsexpired.sort_by{|e| e[params[:sort]]}.reverse!
      else
         @dealsexpired = @dealsexpired.sort_by{|e| e[params[:sort]]}
      end
      @dealsexpired = @dealsexpired.paginate(:page => params[:page_expired], :per_page => 10)

      if params[:search].nil?
         @dealswaiting = Deal.where("isenabled = ?", '0')
      else
         @dealswaiting = Deal.search(params[:search])
         @dealswaiting = @dealswaiting.where(:isenabled => ['0'])
      end

      if params[:direction] == 'desc'
         @dealswaiting = @dealswaiting.sort_by{|e| e[params[:sort]]}.reverse!
      else
         @dealswaiting = @dealswaiting.sort_by{|e| e[params[:sort]]}
      end
      @dealswaiting = @dealswaiting.paginate(:page => params[:page_waiting], :per_page => 10)

      @users = User.all
      @products = User.all
      @locations = Location.all

      respond_to do |format|
         format.html # index.html.erb
         format.json { render json: @deals }
      end
   end


   def show

      @products = Product.all
      @deal = Deal.find(params[:id])
      @locations = Location.all
      @successfulusers = User.all(:joins => :troopcompletes, :conditions => {:troopcompletes => {:deal_id => @deal.id}})
      @currenttroopers = User.all(:joins => :trooplinks, :conditions => {:trooplinks => {:deal_id => @deal.id}})
      @comments = @deal.comments.recent.limit(10).reverse

      render :layout => "application"
   end


   def new
      @product = Product.find(params[:id])
      @deal = Deal.new
      @products = Product.all
      @users = User.all
      @locations = Location.all
      respond_to do |format|
         format.html # new.html.erb
         format.json { render json: @deal }
      end
   end


   def add_new_comment

      deal = Deal.find(params[:id])
      deal.comments.create(params[:comment])
      redirect_to :action => :show, :id => deal

   end


   def modalshow
      @deal = Deal.find(params[:id])
      @locations = Location.all

      respond_to do |format|
         format.html # show.html.erb
         format.json { render json: @deal }
      end
   end


   def edit 
      @deal = Deal.find(params[:id])
      @locations = Location.all
   end


   def create
      @deal = Deal.new(params[:deal])

      @product = Product.find(@deal.product_id)

      respond_to do |format|
         if @deal.save
            @dealsaved = true
            format.html { redirect_to '/', notice: ("Thank you for submitting this offer for " + @deal.product.name + ". Once it's been confirmed we'll post it on FRNZY.") }
           format.js
         else
          @dealsaved = false
          format.html { render action: "new" }
          format.js
         end
      end
   end


   def update
      @deal = Deal.find(params[:id])
      @locations = Location.all

      respond_to do |format|
         if @deal.update_attributes(params[:deal])
            
            if @deal.previous_changes.key? "isenabled"
             if @deal.isenabled == 1
               @deal.send_want_emails
             end
            end

            format.html { redirect_to admin_deals_path, notice: 'Group has been successfully updated.' }
            format.json { head :no_content }
         else
            format.html { render action: "edit" }
            format.json { render json: @deal.errors, status: :unprocessable_entity }
         end
      end
   end

   def destroy
      @deal = Deal.find(params[:id])
      @deal.destroy

      respond_to do |format|
         format.html { redirect_to admin_deals_path }
         format.json { head :no_content }
      end
   end


   private


   def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : "auction_end"
   end

   def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
   end

   def check_expirary
      @deals_checker = Deal.where("isenabled = ? AND auction_end <= ? AND status = ?", '1', DateTime.now.utc, '1')
      @deals_checker.each do | deal |

         if (deal.trooplinks.count >= deal.troop_limit)
            deal.status = '2';
            deal.end_count = deal.trooplinks.count

            deal.trooplinks.each do |trooplink|
               Troopcomplete.create(:user_id => trooplink.user_id, :deal_id => trooplink.deal_id, :transaction_status => 0, :order_id => trooplink.order_id)
               #congratulations email
               @user = User.find(trooplink.user_id)
               @user.send_troop_ended(trooplink)
               trooplink.destroy
            end

         else

            deal.status = '3';

            deal.end_count = deal.trooplinks.count

            if deal.end_count > 0

               deal.trooplinks.each do |trooplink|

                  @gateway ||= PaypalExpressGateway.new(
                  :login => PaypalLogin.login,
                  :password => PaypalLogin.password,
                  :signature => PaypalLogin.signature,
                  )

                  #refund = @gateway.transfer(trooplink.order.total * 100, trooplink.order.paypal_email, :currency => 'GBP', :subject => "FRNZY refund", :note => trooplink.deal.product.name)
                  refund = @gateway.refund nil, trooplink.order.transactionid

                  if refund.success?

                     @order = Order.new
                     @order.attributes = {:transactionid =>  trooplink.order.transactionid, :paypal_email => trooplink.order.paypal_email, :paypal_name => trooplink.order.paypal_name, :user_id => trooplink.user_id, :total => trooplink.order.total, :order_type => 1, :deal_id => trooplink.deal_id }
                     @order.save!

                  else

                     @order = Order.new
                     @order.attributes = {:transactionid =>  trooplink.order.transactionid, :paypal_email => refund.message, :user_id => trooplink.user_id, :total => trooplink.order.total, :order_type => 1, :deal_id => trooplink.deal_id }
                     @order.save!

                  end

                  Troopfail.create(:user_id => trooplink.user_id, :deal_id => trooplink.deal_id, :order_id => @order.id)
                  Like.create(:user_id => trooplink.user_id, :product_id => deal.product_id)
                  #failure email
                  @user = User.find(trooplink.user_id)
                  @user.send_troop_failed(trooplink)
                  trooplink.destroy
               end
            end
         end
         deal.save
      end
   end

end

app/views/deals/modalshow.html.erb
<h2>Troop : <%= raw @deal.product.name %>&nbsp;<% if current_user %>
<% if current_user.role_id == 3 %>
<% end %>
<% end %></h2>


<p>
  <b>Merchant:</b>
   <%= link_to @deal.user.username, @deal.user, :class => "" %>
</p>

<p>
  <b>Product:</b>
  <%= link_to @deal.product.name, @deal.product, :class => "" %>
</p>

<p>
  <b>Unit price:</b>
  <%= @deal.price %>
</p>

<p>
  <b>Troop limit:</b>
  <%= @deal.troop_limit %>
</p>


<p>
  <b>Auction end date:</b>
  <%= @deal.auction_end %>
</p>




<% if current_user %>
<% if current_user.role_id == 3 %>
			
<div id="trooplink_<%= @deal.id %>">
	<%= render 'trooplinks/trooplink_button', :deal => @deal %> 
</div>

<% end %>
	<% else %>
			
			<%= link_to 'Login to access deal', login_path, :class => "btn" %></td>
		
		<% end %>

app/views/deals/show.html.erb
<%
meta og: {
  title: ('FRNZY / ' + @deal.product.name),
  description: ("Check out this exclusive group deal for " + @deal.product.name + " on FRNZY. But hurry, it’s only available for a limited time!"),
  image: @deal.product.product_image.url(:square)
}
%>



<div class = "page_wrapper">

	<% title ('FRNZY / ' + @deal.product.name) %>	
	<% set_meta(:title => ('FRNZY / ' + @deal.product.name), :description => (@deal.product.description)) %>

	<!--0. Lorem ipsum-->
	<% showtroop = false %>
	<% if @deal.isenabled == 1 %>
	<% showtroop = true %>
	<% end %>
	<% if current_user %>
		<% if current_user.role_id == 1 %>
		<% showtroop = true %>
		<% end %>
	<% end %>

	<% if showtroop == true %>


		<!--0. Deal title-->
		<div class="shopSaveShareMsg2">
		    <div class="shopSaveShareTxt2">
		        <ul>
					<li class="selected profileheader">
		                <%= raw @deal.product.name %>
		                 <span class = "hosted_by_text" style = "color:#777777;font-size:15px">&nbsp;hosted by&nbsp;</span>
		                 <%= render @deal.user %>
		            </li>
		        </ul>
		    </div>
		</div>


		<!--1. Deal image-->
		<div class="column_responsive">
			<div class = "product_top_left" style = "position:relative;">
				<%= image_tag @deal.product.product_image.url(:medium) %>
				<%= link_to @deal, :class=> "product_offer frnzyHeadBtn_saving large_deal" do %>
					<%= @deal.percentsaving %>%
					<div class="product_offer_smltxt">OFF</div>
				<% end %>
			</div>
		</div>


		<!--2. Deal content-->
		<div class="column_responsive" style = "float:right;">
			<div class = "product_top_middle minheightdesktop">

				<% if @deal.isenabled == 1 %>
					<div style="float:right;">
						<% if current_user %>
							<% if trooplink = current_user.trooplinks.find_by_deal_id(@deal.id) %>
								<a href="#" style = "margin-left:0px !important;" class="join_troop_btn frnzyHeadBtn right static">
									<%= @deal.trooplinks.count %>/<%= @deal.troop_limit.round() %>
									<div class="product_want_smltxt">joined</div>
								</a>
							<% else %>
								<% if @deal.status == '1' %>
									<% if (current_user.role_id == 3) %>
										<% if @deal.trooplinks.count >= @deal.troop_limit %>
											<%= link_to cart_path(:deal_id => @deal), :method => 'POST', :class=> "join_troop_btn frnzyHeadBtn right static noleftmartingplease"  do %>
												JOIN
												<div class="product_want_smltxt">deal</div>
											<% end %>
										<% else %>
											<%= link_to cart_path(:deal_id => @deal), :method => 'POST', :class=> "join_troop_btn frnzyHeadBtn right static noleftmartingplease"  do %>
												JOIN
												<div class="product_want_smltxt"><%= @deal.trooplinks.count %>/<%= @deal.troop_limit.round() %></div>
											<% end %>
										<% end %>
									<% else %>
										<a style = "margin-left:0px !important;" rel="nofollow" class="join_troop_btn frnzyHeadBtn right static">
										JOINED
											<div class="product_want_smltxt">
												<%= @deal.trooplinks.count %>/<%= @deal.troop_limit.round() %>
											</div>
										</a>
									<% end %>	
								<% else %>
									<a style = "margin-left:0px !important;" rel="nofollow" class="join_troop_btn frnzyHeadBtn right static">
										DONE
										<div class="product_want_smltxt">
											deal
										</div>
									</a>
								<% end %>
							<% end %>
						<% else %>
							<% if @deal.status == '1' %>
								<a style = "margin-left:0px !important;" href="#myModal" data-toggle="modal" class="join_troop_btn frnzyHeadBtn right static">
									JOIN
									<div class="product_want_smltxt"><%= @deal.trooplinks.count %>/<%= @deal.troop_limit.round() %></div>
								</a>
							<% end %>
						<% end %>

						<%= link_to share_deal_path(@deal), :class => "product_share_btn frnzyHeadBtn static", :remote => true do %>
							SHARE
							<div class="product_want_smltxt">deal</div>
						<% end %>

						<!-- <a class="product_deal_btn frnzyHeadBtn superleft largerMainFont static" style="display: block">
							<%= @deal.percentsaving %>%
							<div class="product_want_smltxt">off</div>
						</a> -->

					</div>
				<% else %>
					Group disabled <%= link_to 'click here',  deal_path(@deal, :deal => { :isenabled => 1,  :status => 1}), :method => :put, :class => "btn btn-mini", :confirm => "Are you sure?" %> to enable this deal.<br><br>	
				<% end %>

				<div class = "frenzyprice">
					<p style = "margin-top:0px;">RRP: <%= number_to_currency(@deal.troop_rrp, :unit => "£") %>
						<br>
						<span style = "margin-top:5px;display:block;font-size:20px;margin-bottom:20px;line-height:25px;">FRNZY Deal price: <span style="font-size: 1em; color: #EF0000;"><%= number_to_currency(@deal.price, :unit => "£") %></span></span>
					</p>
				</div>		

				<!-- <p><strong>Product:</strong> <%# link_to @deal.product.name, @deal.product, :class => "" %> -->
				<!-- <p><strong>Troop location:</strong> <%# link_to @deal.location.region, @deal.location, :class => "" %></p> -->
				<!-- <p><strong>Product description:</strong> <%# @deal.product.description %></p> -->

				<% if @deal.status == '1' ||  @deal.status == '2'  ||  @deal.status == '3' %>
					<div class = "troop_status_1" >
					 	<div style="margin-top: 60px;margin-bottom: 0px;" id="frnzy_timer" class = "frnzy_timer_deal">
							<div id="countdown_timer" class="countdown_timer"></div><!-- Countdown values -->
							          
							<div id="countdown_clock" class="countdown_clock">
							  <canvas class="circular_countdown_ends" width="60" height="60"></canvas>
							  <canvas class="circular_countdown_days" width="60" height="60"></canvas>
							  <canvas class="circular_countdown_hours" width="60" height="60"></canvas>
							  <canvas class="circular_countdown_minutes" width="60" height="60"></canvas>
							  <canvas class="circular_countdown_seconds" width="60" height="60"></canvas>
							</div>

							<script>
								$(document).ready(function($){
									var endDate = new Date(<%= @deal.auction_end.to_i * 1000%>);
									var settings = {};

									settings.until = endDate;

									if(endDate < new Date()){
										//This one has expired - set the rings to be gray...
										settings.strokeEndsColor = 'rgba(240,240,240,1.0)';
										settings.strokeDaysColor = 'rgba(240,240,240,1.0)';
										settings.strokeHoursColor = 'rgba(240,240,240,1.0)';
										settings.strokeMinutesColor = 'rgba(240,240,240,1.0)';
										settings.strokeSecondsColor = 'rgba(240,240,240,1.0)';
									}
									else{
										settings.strokeEndsBackgroundColor = 'rgba(0,0,0,0.06)';
										settings.strokeEndsColor = 'rgba(0,0,0,0.25)';//'rgba(255,199,0,1)';
										settings.strokeDaysBackgroundColor = 'rgba(0,0,0,0.06)';
										settings.strokeDaysColor = 'rgba(0,0,0,0.25)';//'rgba(3,164,0,1)';
										settings.strokeHoursBackgroundColor = 'rgba(0,0,0,0.06)';
										settings.strokeHoursColor = 'rgba(0,0,0,0.25)';//'rgba(255,31,136,1)';
										settings.strokeMinutesBackgroundColor = 'rgba(0,0,0,0.06)';
										settings.strokeMinutesColor = 'rgba(0,0,0,0.25)';//'rgba(0,179,247,1)';
										settings.strokeSecondsBackgroundColor = 'rgba(0,0,0,0.06)';
										settings.strokeSecondsColor = 'rgba(0,0,0,0.25)';//'rgba(244,0,0,1)';
									}

									$('#frnzy_timer').circularCountdown(settings);
									<% if @deal.status == '2' %>
										$('#frnzy_timer').find('.ends').html("<em>DONE</em> deal");
									<% end %>
								});
							</script>
						</div>
					</div>					
				<% end %>

				<!-- <p style="padding-right: 0px;margin-top:40px;"><%= @deal.product.description %></p> -->
				<% if @deal.status == '1' %>
					<!-- TODO: Change font below with JEZ. -->
					<div class = "currentroopersneeded">

	<% if current_user %>

				<div class="invite_container" style = "padding-top:20px;">
					<%= link_to invite_deal_path(@deal), :class => "fa-button", :remote => true do %>
						<i class="fa fa-user-plus"></i>Invite</a>
					<% end %>
				</div>
<% end %>

				<div style = "width:100%;float:left;padding-top:10px;">
						<% if @currenttroopers.empty?%>		
							 Only <%= @deal.troop_limit.round() %> more needed!
						<% else %>
							<% if @deal.troop_limit.round() > @deal.trooplinks.count %>
								Only <%= @deal.troop_limit.round() - @deal.trooplinks.count %> more needed!
							<% else %>
								<!-- Deal acitve!! -->
							<% end %>
						<% end %>

						</div>
					</div>
				<% end %>

				


				<% if @deal.status == '3' %>
					<%#Troop expired %>
				<% end %>	

			</div>
		</div>






		<!--4. Product wants-->
		<% if @deal.status != '3' %>
			<div class="column_responsive peoplewant" style = "margin-bottom: 20px;clear: left !important;">
				<div class = "currentroopers">
					<strong>
						<h2>People who have joined this deal</h2>
						<% unless @currenttroopers.empty?%>		

							<% @currenttroopers.each do |user| %>
								<% unless user == nil %>
									<%= render user %>
								<% end %>
							<% end %>
						<% end %>
					</strong>
				</div>
			</div>
		<% end %>





		<!--3. Deal discuss + comments-->
		<div class="column_responsive comments_here" style = "clear:right;margin-bottom:20px;">
			<div class="product_top_left" id="comments_box">

				<h2 style = "text-align:center;margin-top:5px;" ><% unless current_user %><a href = "#" style = "" class="open_login">Sign in to comment on this deal</a><% else %>Comment on this deal<% end %></h2>
				<% if current_user %>
					<div class = "postcomment">
						<%= form_tag "/deals/add_new_comment" do %>
					    	<%= hidden_field_tag "id", @deal.id %>
					    	<%= hidden_field_tag "comment[user_id]", current_user.id %>
							<textarea onkeyup="textLimit(this, 140);" name="comment[comment]" id="comment_comment" rows="2"></textarea>
							<a style = "float:right;width:21%;text-align:center;line-height: 45px;height: 45px;" href="#" class="fa-button add_post">						<i class="fa fa-pencil"></i>Post</a>
					    	<%= submit_tag "POST", :class  => "hide_post_button" %>
					  	<% end %>
				<% else %>
					<div class = "postcomment" style = "text-align:center;padding-bottom:10px;">
				<% end %>

				<% unless @comments.empty? %>
					<%= render @comments %>
				<% end %>
				
				</div>

				<!--Not seen yet-->
				<% if current_user %>
					<% if (current_user.id == @deal.user_id) || (current_user.role_id == 1) %>
						<% if @deal.status == '2' %>
							<div class = "product_bottom">
								<div class = "product_bottom_left2">
									<h3>Succesfull Members</h3>
									<table class = "table">
										<tr>
											<th>Image</th>
											<th>Username</th>
											<th>Email</th>
											<th>Firstname</th>
											<th>Lastname</th>
											<th>Postal Address</th>
										</tr>
										<% @successfulusers.each do |user| %>
										   <tr <%if (user.isenabled == 0) %>class = 'error'<% end %> >
												<td><%= link_to (image_tag user.photo.url(:extrasmall)), user, :class => "troop_successful_admin_list" %></td>
												<td><%= link_to user.username, user, :class => "" %></td>
												<td><%= user.email %></td>
												<td><%= user.first_name %></td>
												<td><%= user.last_name %></td>
												<td>
													<%= user.house_number %>,
													<%= user.address %>, 
													<% if user.address_2 != '' %><%= user.address_2 %>, <% end %>
													<%= user.city %>, 
													<%= user.postcode %>, 
													<%= user.country %>
												</td>
									      </tr>
										<% end %>
									</table>
								</div>
							</div>
						<% end %>
					<% end %>
				<% end %>
				<!--Not seen yet-->

			</div>
		</div>




	<% else %>
		

		<% if @product.isenabled == 0 %>
			<div style="width:100%;text-align:center;margin-top:20px;margin-bottom: -10px;">
				Deal not enabled.
			</div>
		<% end %>


	<% end %>

	<script type="text/javascript">

		function textLimit(field, maxlen) {
		if (field.value.length > maxlen + 1)
		alert('140 character limit reached.');
		if (field.value.length > maxlen)
		field.value = field.value.substring(0, maxlen);
		}

	</script>

</div>	