config/routes.rb
St001::Application.routes.draw do

   resources :pages

   get "/how_it_works" => "pages#how", :as => "how_it_works"
   get "/win_urBeats_by_dre" => "pages#beats", :as => "win_urBeats_by_dre"

   get "email_confirms/new"

   match '/sharrre' => 'Rsocialize#sharrre'

   match '/deals/new/:id' => 'deals#new', :as => 'newdealwithproduct'


   get "invite/products/:id/" => "products#invite", :as => "invite_product"
   get "invite/deal/:id/" => "deals#invite", :as => "invite_deal"
   get "invite/home/" => "home#invite", :as => "invite_home"
   post "invite/email/" => "referral#email", :as => "invite_email"
   match 'invite/:id' => 'referral#redirect', :as => 'accept_referral'

   resources :groups
   resources :troopfails
   resources :troopcompletes
   resources :locations
   resources :categories
   resources :trooplinks
   resources :deals
   resources :orders
   resources :likes, :only => [:create, :destroy]
   resources :password_resets

   resources :products do
      post :want_product, :on => :member
   end

   get "home/index"
   resources :roles
   resources :likes
   resource :cart

   get "paypal_express/checkout"
   get "paypal_express/cancel"
   get "paypal_express/review"
   get "paypal_express/purchase"
   get "paypal_express/refund"
   get "paypal_express/notify"
   post "paypal_express/notify"
   
   get "/check_duplicates" => "products#duplicate", :as => "product_duplicate"
   get "/like_and_view/:id/" => "products#like_and_view", :as =>"producut_like_and_view"
   get "/product_url_scrape" => "scrape#scrape", :as => "scrape_url_images"

   match "/products/add_new_comment" => "products#add_new_comment", :as => "add_new_comment_to_produdcts", :via => [:post]
   match "/deals/add_new_comment" => "deals#add_new_comment", :as => "add_new_comment_to_deals", :via => [:post]
  
   get "remove_comment/:id/" => "products#remove_comment", :as => "remove_comment"
   
   get "shareproduct/:id/" => "products#share", :as => "share_product"
   get "sharedeal/:id/" => "deals#share", :as => "share_deal"

   get "followuser/:id/" => "follows#followuser", :as => "followuser"
   get "unfollowuser/:id/" => "follows#unfollowuser", :as => "unfollowuser"
   get "following/:id/" => "follows#following", :as => "following"
   get "followers/:id/" => "follows#followers", :as => "followers"

   match '/search/:query/:qcategory' => 'search#search', :as => 'search'
   #match '/search/:query' => 'search#search', :as => 'search'
   
   match '/search' => 'search#search', :as => 'search'

   match 'auth/:provider/callback', to: 'sessions#createfacebook'
   match 'auth/failure', to: redirect('/')
   match 'signout', to: 'sessions#facebook', as: 'signout'


   get "logout" => "sessions#destroy", :as => "logout"
   get "login" => "sessions#new", :as => "login"
   get "admin_users" => "users#view_user", :as => "admin_users"
   get "admin_merchants" => "users#view_merchant", :as => "admin_merchants"
   get "admin_products" => "products#view", :as => "admin_products"
   get "admin_deals" => "deals#view", :as => "admin_deals"
   get "admin_locations" => "locations#view", :as => "admin_locations"
   get "admin_categories" => "categories#view", :as => "admin_categories"
   get "admin_orders" => "orders#view", :as => "admin_orders"
   get "admin_referrals" => "referral#view", :as => "admin_referrals"


   get "admin_pages" => "pages#view", :as => "admin_pages"
   get "register" => "users#new", :as => "register"
   get "dashboard" => "users#dashboard", :as => "userprofile"

   get "sitemap.xml.gz" => "sitemap#file"

   match "/modalshow/:id" => "deals#modalshow"

   root :to => "products#homepage"
   resources :users
   resources :sessions

   get "email_confirms/new"
   resources :email_confirms


   match "/resend/:id" => "users#resend_confirmation_email"

   match 'contactmessager' => 'contactmessager#new', :as => 'contactmessager', :via => :get
   match 'contactmessager' => 'contactmessager#create', :as => 'contactmessager', :via => :post
   
   match 'troops/:id' => 'deals#show', :as => 'troop_catch'

end

app/models/category.rb
class Category < ActiveRecord::Base

   extend FriendlyId
   friendly_id :slug

   has_many :products
   has_many :groups, :dependent => :destroy

   validates_presence_of :name
   validates_presence_of :description
   validates_presence_of :slug
   validates_uniqueness_of :slug

   accepts_nested_attributes_for :products
   attr_accessible :description, :name, :slug

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

   include ActiveMerchant::Billing
   include PaypalExpressHelper

   before_filter :check_expirary
   layout 'application'


   def index
      @categories = Category.all
      @groups = Group.all

      respond_to do |format|
         format.html # index.html.erb
         format.json { render json: @categories }
      end
   end


   def view
      @categories = Category.all
      @groups = Group.all

      respond_to do |format|
         format.html # index.html.erb
         format.json { render json: @categories }
      end
   end


   def show

      if cookies[:wanted_filter].present?
      else
         cookies[:wanted_filter] = {:value => '1',:expires => 1.year.from_now,:path => '/'}
      end

      if cookies[:active_filter].present?
      else
         cookies[:active_filter] = {:value => '1',:expires => 1.year.from_now,:path => '/'}
      end

      if cookies[:done_filter].present?
      else
         cookies[:done_filter] = {:value => '1',:expires => 1.year.from_now,:path => '/'}
      end

      if cookies[:sort_order].present?
      else
         cookies[:sort_order] = {:value => 'Most recent',:expires => 1.year.from_now,:path => '/'}
      end


      @locations = Location.all
      @categories = Category.all
      @category = Category.find(params[:id])

      @groups = Group.where("category_id = ?", @category.id)
      @products = Product.where("isenabled = ? AND category_id = ?", '1', @category.id)
      @deals = Deal.joins(:product).where("category_id = ?", @category.id)


      @users = User.all
      @likes = Like.all


      @deals = @deals.where(:status => ['1','2'])
      if (cookies[:active_filter] == '0') && (cookies[:done_filter] == '0')
         @deals = @deals.where(:status => ['4'])
      elsif (cookies[:active_filter] == '1') && (cookies[:done_filter] == '0')
         @deals = @deals.where(:status => ['1'])
      elsif (cookies[:active_filter] == '0') && (cookies[:done_filter] == '1')
         @deals = @deals.where(:status => ['2'])
      elsif (cookies[:active_filter] == '1') && (cookies[:done_filter] == '1')
         @deals = @deals.where(:status => ['1','2'])
      end

      @deallinks = Trooplink.all


      if cookies[:wanted_filter] == '1'
         @combinedproductsandtroops = (@products + @deals)
      else
         @combinedproductsandtroops = (@deals)
      end

      #SORT BY ELSIFS
      if (cookies[:sort_order] == 'Most recent')
         @combinedproductsandtroops = @combinedproductsandtroops.sort_by{|e| e[:created_at]}.reverse
      elsif (cookies[:sort_order] == 'Oldest')
         @combinedproductsandtroops = @combinedproductsandtroops.sort_by{|e| e[:created_at]}
      elsif (cookies[:sort_order] == 'Troops ending soon')
         @combinedproductsandtroops = @deals.where(:status => ['1']).sort_by{|e| e[:auction_end]}
      elsif (cookies[:sort_order] == 'Most expensive')
         @combinedproductsandtroops = @combinedproductsandtroops.sort_by{|e| e[:price]}.reverse
      elsif (cookies[:sort_order] == 'Best deals')
         @combinedproductsandtroops = @deals.where(:status => ['1'])#@combinedproductsandtroops.sort_by{|e| e[:price]}
      elsif (cookies[:sort_order] == 'Most popular')
         @combinedproductsandtroops = @combinedproductsandtroops.sort_by{|e| e[:popularity]}.reverse
      end

      #ORDER BY ON THIS ARRAY
      @combinedproductsandtroops = @combinedproductsandtroops.paginate(:page => params[:page], :per_page => 15)


      respond_to do |format|
         format.html {render :layout => "application"}
         format.js
      end
      
   end



   def new
      @category = Category.new
      @groups = Group.all

      respond_to do |format|
         format.html # new.html.erb
         format.json { render json: @category }
      end
   end



   def edit
      @category = Category.find(params[:id])
      @groups = Group.all

   end



   def create
      @category = Category.new(params[:category])
      @groups = Group.all

      respond_to do |format|
         if @category.save
            format.html { redirect_to admin_categories_path, notice: 'Category was successfully created.' }
            format.json { render json: @category, status: :created, location: @category }
         else
            format.html { render action: "new" }
            format.json { render json: @category.errors, status: :unprocessable_entity }
         end
      end
   end



   def update
      @category = Category.find(params[:id])

      respond_to do |format|
         if @category.update_attributes(params[:category])
            format.html { redirect_to admin_categories_path, notice: 'Category was successfully updated.' }
            format.json { head :no_content }
         else
            format.html { render action: "edit" }
            format.json { render json: @category.errors, status: :unprocessable_entity }
         end
      end
   end



   def destroy
      @groups = Group.all

      @category = Category.find(params[:id])
      @category.destroy

      respond_to do |format|
         format.html { redirect_to admin_categories_path }
         format.json { head :no_content }
      end
   end



   private

   def check_expirary
      @deals_checker = Deal.where("isenabled = ? AND auction_end <= ? AND status = ?", '1', DateTime.now.utc, '1')
      @deals_checker.each do | deal |

         if (deal.trooplinks.count >= deal.troop_limit)
            deal.status = '2';
            deal.end_count = deal.trooplinks.count

            deal.trooplinks.each do |trooplink|
               Troopcomplete.create(:user_id => trooplink.user_id, :deal_id => trooplink.deal_id, :transaction_status => 0, :order_id => trooplink.order_id)
               #congratulations email
               @user = User.find(trooplink.user_id)
               @user.send_troop_ended(trooplink)
               trooplink.destroy
            end

         else

            deal.status = '3';

            deal.end_count = deal.trooplinks.count

            if deal.end_count > 0

               deal.trooplinks.each do |trooplink|

                  @gateway ||= PaypalExpressGateway.new(
                  :login => PaypalLogin.login,
                  :password => PaypalLogin.password,
                  :signature => PaypalLogin.signature,
                  )

                  #refund = @gateway.transfer(trooplink.order.total * 100, trooplink.order.paypal_email, :currency => 'GBP', :subject => "FRNZY refund", :note => trooplink.deal.product.name)
                  refund = @gateway.refund nil, trooplink.order.transactionid

                  if refund.success?

                     @order = Order.new
                     @order.attributes = {:transactionid =>  trooplink.order.transactionid, :paypal_email => trooplink.order.paypal_email, :paypal_name => trooplink.order.paypal_name, :user_id => trooplink.user_id, :total => trooplink.order.total, :order_type => 1, :deal_id => trooplink.deal_id }
                     @order.save!

                  else

                     @order = Order.new
                     @order.attributes = {:transactionid =>  trooplink.order.transactionid, :paypal_email => refund.message, :user_id => trooplink.user_id, :total => trooplink.order.total, :order_type => 1, :deal_id => trooplink.deal_id }
                     @order.save!

                  end

                  Troopfail.create(:user_id => trooplink.user_id, :deal_id => trooplink.deal_id, :order_id => @order.id)
                  Like.create(:user_id => trooplink.user_id, :product_id => deal.product_id)
                  #failure email
                  @user = User.find(trooplink.user_id)
                  @user.send_troop_failed(trooplink)
                  trooplink.destroy
               end
            end
         end
         deal.save
      end
   end






end

app/views/categories/edit.html.erb
<div class = "page_wrapper" style = "max-width:500px;padding:20px;padding-top:0px; box-sizing: border-box;">

<% if current_user %>
<% if current_user.role_id == 1 %>

	<% title ('FRNZY / Edit ' + @category.name) %>	
<% set_meta(:title => ('FRNZY Edit / ' + @category.name), :description => ('FRNZY / Edit ' + @category.name)) %>

       <%= form_for(@category) do |f| %>
         
         <div class="shopSaveShareMsg2">
          <div class="shopSaveShareTxt2">
              <ul>
                  <li class="selected">
                     Editing <%= @category.name %>       
                  </li>
              </ul>
          </div>
         </div>

         <% if @category.errors.any? %>
            <div id="error_explanation">
               <h2><%= pluralize(@category.errors.count, "error") %> prohibited this user from being saved:</h2>
               <ul>
                  <% @category.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
               </ul>
            </div>
         <% else %>           
         <% end %>

         <div class="frnzyFrmGrp_res">
            <div class="frnzyFrmRight">
               <div class="field">
                  <%#= f.label :last_name %>
                  <%= f.text_field :slug,{placeholder: "slug"} %>
               </div>
               <div class="field">
                  <%#= f.label :username %>
                  <%= f.text_field :name,{placeholder: "name"} %>
               </div>
               <div class="field">
                  <%#= f.label :company %>
                  <%= f.text_field :description,{placeholder: "description"} %>
               </div>
            </div>
         </div>
        
         <div class="frnzyFrmGrp_res">     
            <div class="form_heading">
            </div>
            <div class="frnzyFrmRight">
               <div class="actions">
                  <%= f.submit 'Submit', {:style => 'margin-top:20px;', :class => 'fa-button'} %>  
               </div>
            </div>
         </div>

      <% end %> 

<% end %>
<% end %>
 
</div>

app/views/categories/new.html.erb
<div class = "page_wrapper" style = "max-width:500px;padding:20px;padding-top:0px; box-sizing: border-box;">

<% if current_user %>
<% if current_user.role_id == 1 %>

<% title ('FRNZY / New category') %>	
<% set_meta(:title => ('FRNZY / New category'), :description => ('FRNZY / New category')) %>
	
       <%= form_for(@category) do |f| %>
         
         <div class="shopSaveShareMsg2">
          <div class="shopSaveShareTxt2">
              <ul>
                  <li class="selected">
                     Add new category     
                  </li>
              </ul>
          </div>
         </div>

         <% if @category.errors.any? %>
            <div id="error_explanation">
               <h2><%= pluralize(@category.errors.count, "error") %> prohibited this user from being saved:</h2>
               <ul>
                  <% @category.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
               </ul>
            </div>
         <% else %>           
         <% end %>

         <div class="frnzyFrmGrp_res">
            <div class="frnzyFrmRight">
               <div class="field">
                  <%#= f.label :last_name %>
                  <%= f.text_field :slug,{placeholder: "slug"} %>
               </div>
               <div class="field">
                  <%#= f.label :username %>
                  <%= f.text_field :name,{placeholder: "name"} %>
               </div>
               <div class="field">
                  <%#= f.label :company %>
                  <%= f.text_field :description,{placeholder: "description"} %>
               </div>
            </div>
         </div>
        
         <div class="frnzyFrmGrp_res">     
            <div class="form_heading">
            </div>
            <div class="frnzyFrmRight">
               <div class="actions">
                  <%= f.submit 'Submit', {:style => 'margin-top:20px;', :class => 'fa-button'} %>  
               </div>
            </div>
         </div>

      <% end %> 

<% end %>
<% end %>
 
</div>

app/views/categories/show.html.erb
<% title ('FRNZY / ' + @category.name) %> 
<% set_meta(:title => ('FRNZY / ' + @category.name), :description => ('FRNZY / ' + @category.name)) %>
  
<% if cookies[:wanted_filter].present? %>
<% else 
  cookies[:wanted_filter] = {
  :value => '1',
  :expires => 1.year.from_now,
  :path => '/'
}
%>
<% end %>

<% if cookies[:active_filter].present? %>
<% else 
  cookies[:active_filter] = {
  :value => '1',
  :expires => 1.year.from_now,
  :path => '/'
}
%>
<% end %>

<% if cookies[:done_filter].present? %>
<% else 
  cookies[:done_filter] = {
  :value => '1',
  :expires => 1.year.from_now,
  :path => '/'
}
%>
<% end %>

<div class="shopSaveShareMsg2">
    <div class="shopSaveShareTxt2">
        <ul>
            <li class="selected">
                <%= @category.name %>
            </li>
        </ul>
    </div>
</div>

<div class = 'isotope' id = "fade_on_load" style = "opacity:0;">
  <%= render @combinedproductsandtroops %>  
</div>
     
<div class="clearfix">
  <div id = "endlesspagination">
    <%= will_paginate @combinedproductsandtroops, previous_label: h("<"), next_label: h(">") %>
  </div>    
</div>

app/views/categories/show.js.erb
var $newItems = $('<%= j render(@combinedproductsandtroops) %>');
$('.isotope').isotope( 'insert', $newItems );

$('.product_header').delay(750).fadeTo("slow", 1);

<% if @combinedproductsandtroops.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@combinedproductsandtroops) %>');
<% else %>
  $('.pagination').remove();
<% end %>


//ISOTOPE AGAIN SO IT CORRECT THE WITDTH OF NEW ITEMS LETS TEST FILTERS WIHT THIS???


var $container = $('.isotope'),
colWidth = function () {
	var w = $container.width(), 
	columnNum = 1,
	columnWidth = 0;
//Select what will be your porjects columns according to container widht
if (w > 2000)     { columnNum  = 10; }  
else if (w > 1840) { columnNum  = 9; }  
else if (w > 1640) { columnNum  = 8; }  
else if (w > 1440) { columnNum  = 7; }  
else if (w > 1240) { columnNum  = 6; }  
else if (w > 1040) { columnNum  = 5; }  
else if (w > 850) { columnNum  = 4; }  
else if (w > 768) { columnNum  = 3; }  
else if (w > 480) { columnNum  = 3; }
else if (w > 300) { columnNum  = 2; }
columnWidth = Math.floor(w/columnNum);

//Default item width and height
$container.find('.frnzy_item').each(function() {
	var $item = $(this), 
	width = columnWidth,
	height = columnWidth;
	$item.css({ width: width, height: height });
}); 

//2x width item width and height
$container.find('.width2').each(function() {
	var $item = $(this), 
	width = columnWidth*2,
	height = columnWidth;
	$item.css({ width: width, height: height });
}); 

//2x height item width and height
$container.find('.height2').each(function() {
	var $item = $(this), 
	width = columnWidth,
	height = columnWidth*2;
	$item.css({ width: width, height: height });
}); 

//2x item width and height
$container.find('.width2.height2').each(function() {
	var $item = $(this), 
	width = columnWidth*2,
	height = columnWidth*2;
	$item.css({ width: width, height: height });
}); 
return columnWidth;
},
isotope = function () {
	$container.isotope({
		resizable: true,
		itemSelector: '.frnzy_item',
		masonry: {
			columnWidth: colWidth(),
			gutterWidth: 10
		}
	});
};
isotope(); 

// bind filter button click
$('.isotope-filters').on( 'click', 'button', function() {
	var filterValue = $( this ).attr('data-filter');
	$container.isotope({ filter: filterValue });
});

// change active class on buttons
$('.isotope-filters').each( function( i, buttonGroup ) {
	var $buttonGroup = $( buttonGroup );
	$buttonGroup.on( 'click', 'button', function() {
		$buttonGroup.find('.active').removeClass('active');
		$( this ).addClass('active');
	});
}); 

app/views/categories/view.html.erb
<link rel="stylesheet" href="/adminbootstrap/bootstrap.min.css" />

<div class = "boostrap_admin_menu">

<% title ('FRNZY / Categories') %>	
<% set_meta(:title => ('FRNZY / Categories'), :description => ('FRNZY / Categories')) %>

<% if current_user %>
<% if current_user.role_id == 1 %>

<div class="navbar admin_nav">
	<div class="navbar-inner">
		<a href="#" class="subbrand">Listing all categories</a>

<%= link_to 'New Category', new_category_path, :class => "btn btn-danger" %>
<%= link_to 'New Subcategory', new_group_path, :class => "btn btn-danger" %><br>
<%= render 'shared/admin_menu' %>    
    
	</div>
</div>


<table class = "table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th class = "nomobile"></th>
    <th class = "nomobile"></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td class = "nomobile"><%= link_to 'View', category, :class => "btn btn-mini" %></td>
    <td class = "nomobile"><%= link_to 'Edit', edit_category_path(category), :class => "btn btn-mini" %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %></td>
  </tr>

  <% category.groups.each do |group| %>
    <tr>
      <td>&nbsp</td>
      <td><%= group.name %></td>
      <td class = "nomobile"><%= link_to 'View', group, :class => "btn btn-mini" %></td>
      <td class = "nomobile"><%= link_to 'Edit', edit_group_path(group), :class => "btn btn-mini" %></td>
      <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %></td>
    </tr>
  <% end %>

<% end %>


</table>



<% end %>
<% end %>
</div>