config/routes.rb
St001::Application.routes.draw do

   resources :pages

   get "/how_it_works" => "pages#how", :as => "how_it_works"
   get "/win_urBeats_by_dre" => "pages#beats", :as => "win_urBeats_by_dre"

   get "email_confirms/new"

   match '/sharrre' => 'Rsocialize#sharrre'

   match '/deals/new/:id' => 'deals#new', :as => 'newdealwithproduct'


   get "invite/products/:id/" => "products#invite", :as => "invite_product"
   get "invite/deal/:id/" => "deals#invite", :as => "invite_deal"
   get "invite/home/" => "home#invite", :as => "invite_home"
   post "invite/email/" => "referral#email", :as => "invite_email"
   match 'invite/:id' => 'referral#redirect', :as => 'accept_referral'

   resources :groups
   resources :troopfails
   resources :troopcompletes
   resources :locations
   resources :categories
   resources :trooplinks
   resources :deals
   resources :orders
   resources :likes, :only => [:create, :destroy]
   resources :password_resets

   resources :products do
      post :want_product, :on => :member
   end

   get "home/index"
   resources :roles
   resources :likes
   resource :cart

   get "paypal_express/checkout"
   get "paypal_express/cancel"
   get "paypal_express/review"
   get "paypal_express/purchase"
   get "paypal_express/refund"
   get "paypal_express/notify"
   post "paypal_express/notify"
   
   get "/check_duplicates" => "products#duplicate", :as => "product_duplicate"
   get "/like_and_view/:id/" => "products#like_and_view", :as =>"producut_like_and_view"
   get "/product_url_scrape" => "scrape#scrape", :as => "scrape_url_images"

   match "/products/add_new_comment" => "products#add_new_comment", :as => "add_new_comment_to_produdcts", :via => [:post]
   match "/deals/add_new_comment" => "deals#add_new_comment", :as => "add_new_comment_to_deals", :via => [:post]
  
   get "remove_comment/:id/" => "products#remove_comment", :as => "remove_comment"
   
   get "shareproduct/:id/" => "products#share", :as => "share_product"
   get "sharedeal/:id/" => "deals#share", :as => "share_deal"

   get "followuser/:id/" => "follows#followuser", :as => "followuser"
   get "unfollowuser/:id/" => "follows#unfollowuser", :as => "unfollowuser"
   get "following/:id/" => "follows#following", :as => "following"
   get "followers/:id/" => "follows#followers", :as => "followers"

   match '/search/:query/:qcategory' => 'search#search', :as => 'search'
   #match '/search/:query' => 'search#search', :as => 'search'
   
   match '/search' => 'search#search', :as => 'search'

   match 'auth/:provider/callback', to: 'sessions#createfacebook'
   match 'auth/failure', to: redirect('/')
   match 'signout', to: 'sessions#facebook', as: 'signout'


   get "logout" => "sessions#destroy", :as => "logout"
   get "login" => "sessions#new", :as => "login"
   get "admin_users" => "users#view_user", :as => "admin_users"
   get "admin_merchants" => "users#view_merchant", :as => "admin_merchants"
   get "admin_products" => "products#view", :as => "admin_products"
   get "admin_deals" => "deals#view", :as => "admin_deals"
   get "admin_locations" => "locations#view", :as => "admin_locations"
   get "admin_categories" => "categories#view", :as => "admin_categories"
   get "admin_orders" => "orders#view", :as => "admin_orders"
   get "admin_referrals" => "referral#view", :as => "admin_referrals"


   get "admin_pages" => "pages#view", :as => "admin_pages"
   get "register" => "users#new", :as => "register"
   get "dashboard" => "users#dashboard", :as => "userprofile"

   get "sitemap.xml.gz" => "sitemap#file"

   match "/modalshow/:id" => "deals#modalshow"

   root :to => "products#homepage"
   resources :users
   resources :sessions

   get "email_confirms/new"
   resources :email_confirms


   match "/resend/:id" => "users#resend_confirmation_email"

   match 'contactmessager' => 'contactmessager#new', :as => 'contactmessager', :via => :get
   match 'contactmessager' => 'contactmessager#create', :as => 'contactmessager', :via => :post
   
   match 'troops/:id' => 'deals#show', :as => 'troop_catch'

end

app/models/troopfail.rb
class Troopfail < ActiveRecord::Base

   belongs_to :user
   belongs_to :deal
   belongs_to :order

   attr_accessible :deal_id, :user_id, :order_id, :refund_id
   validates_uniqueness_of :deal_id, :scope => :user_id

end

app/controllers/troopfails_controller.rb
class TroopfailsController < ApplicationController

   layout 'application'



   def index
      @dealfails = Troopfail.all

      respond_to do |format|
         format.html # index.html.erb
         format.json { render json: @dealfails }
      end
   end




   def show
      @dealfail = Troopfail.find(params[:id])

      respond_to do |format|
         format.html # show.html.erb
         format.json { render json: @dealfail }
      end
   end





   def new
      @dealfail = Troopfail.new

      respond_to do |format|
         format.html # new.html.erb
         format.json { render json: @dealfail }
      end
   end




   def edit
      @dealfail = Troopfail.find(params[:id])
   end





   def create
      @dealfail = Troopfail.new(params[:troopfail])

      respond_to do |format|
         if @dealfail.save
            format.html { redirect_to @dealfail, notice: 'Troopfail was successfully created.' }
            format.json { render json: @dealfail, status: :created, location: @dealfail }
         else
            format.html { render action: "new" }
            format.json { render json: @dealfail.errors, status: :unprocessable_entity }
         end
      end
   end






   def update
      @dealfail = Troopfail.find(params[:id])

      respond_to do |format|
         if @dealfail.update_attributes(params[:troopfail])
            format.html { redirect_to @dealfail, notice: 'Troopfail was successfully updated.' }
            format.json { head :no_content }
         else
            format.html { render action: "edit" }
            format.json { render json: @dealfail.errors, status: :unprocessable_entity }
         end
      end
   end






   def destroy
      @dealfail = Troopfail.find(params[:id])
      @dealfail.destroy

      respond_to do |format|
         format.html { redirect_to troopfails_url }
         format.json { head :no_content }
      end
   end
end

app/views/troopfails/_form.html.erb
<%= form_for(@dealfail) do |f| %>
  <% if @dealfail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dealfail.errors.count, "error") %> prohibited this troopfail from being saved:</h2>

      <ul>
      <% @dealfail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :deal_id %><br />
    <%= f.number_field :deal_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/troopfails/edit.html.erb
<h1>Editing troopfail</h1>

<%= render 'form' %>

<%= link_to 'Show', @dealfail %> |
<%= link_to 'Back', troopfails_path %>

app/views/troopfails/index.html.erb
<h1>Listing troopfails</h1>

<table>
  <tr>
    <th>User</th>
    <th>Troop</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dealfails.each do |troopfail| %>
  <tr>
    <td><%= troopfail.user_id %></td>
    <td><%= troopfail.deal_id %></td>
    <td><%= link_to 'Show', troopfail %></td>
    <td><%= link_to 'Edit', edit_troopfail_path(troopfail) %></td>
    <td><%= link_to 'Destroy', troopfail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Troopfail', new_troopfail_path %>

app/views/troopfails/new.html.erb
<h1>New troopfail</h1>

<%= render 'form' %>

<%= link_to 'Back', troopfails_path %>

app/views/troopfails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @dealfail.user_id %>
</p>

<p>
  <b>Troop:</b>
  <%= @dealfail.deal_id %>
</p>


<%= link_to 'Edit', edit_troopfail_path(@dealfail) %> |
<%= link_to 'Back', troopfails_path %>